name: Python application
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  LANG: "pt_BR.UTF-8"
jobs:
  tests:
    name: App Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: flask_github_actions_test
          POSTGRES_USER: flask_github_actions
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set pt_BR Locale
        run: |
            sudo locale-gen pt_BR.UTF-8
            sudo update-locale LANG=pt_BR.UTF-8

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt;

      - name: Test with pytest
        env:
          FLASK_APP: src
          DATABASE_URL_TST: postgres://flask_github_actions:postgres@postgres:5432/flask_github_actions_test
        run: |
          export LC_ALL="pt_BR.UTF-8"
          export LC_CTYPE="pt_BR.UTF-8"
          sudo dpkg-reconfigure locales
          pytest -v --cov=src