name: Python application
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  LANG: "pt_BR.UTF-8"
jobs:
  tests:
    name: App Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: flask_github_actions_test
          POSTGRES_USER: flask_github_actions
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set pt_BR Locale
        run: |
            sudo locale-gen pt_BR.UTF-8
            sudo update-locale LANG=pt_BR.UTF-8

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt;

      - name: Unit Tests
        env:
          FLASK_APP: src
          FLASK_ENV: testing
          DATABASE_URL_TST: postgresql://flask_github_actions:postgres@localhost:5432/flask_github_actions_test
        run: |
          pytest tests/unit/

      - name: Integration Tests
        env:
          FLASK_APP: src
          DATABASE_URL_TST: postgresql://flask_github_actions:postgres@localhost:5432/flask_github_actions_test
        run: |
          pytest tests/integration/

  build:
    name: Heroku Deploy
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "flask-finances" #Must be unique in Heroku
          heroku_email: "willsouzafilho@gmail.com"